docker-compose:  switch to short-hand syntax for volumes. Long-hand syntax for volumes now causes podman to choke with the following error in latest podman from Fedora 34:
ERROR: for etc_psql-rhpam_1  Cannot create container for service psql-rhpam: runtime error: invalid memory address or nil pointer dereference